FROM microsoft/iis

#RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\CanvasGrid\*

RUN powershell -NoProfile -Command New-Item -Path C:\inetpub\wwwroot\ -Name "CanvasGrid" -ItemType "directory"

WORKDIR /inetpub/wwwroot/CanvasGrid

ADD ./dist/CanvasGridUI .

EXPOSE 80
