FROM microsoft/iis

#RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\CanvasGrid\*

RUN powershell -NoProfile -Command New-Item -Path C:\inetpub\wwwroot\ -Name "Ezines" -ItemType "directory"

WORKDIR /inetpub/wwwroot/CanvasGrid

COPY /dist/CanvasGridUI .

EXPOSE 80
