FROM microsoft/iis

#RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\CanvasGrid\*

RUN powershell -NoProfile -Command New-Item -Path C:\inetpub\wwwroot\ -Name "canvasgrid" -ItemType "directory"

COPY c:/builds/canvasgrid/canvasgridui/dist/canvasgridui c:/inetpub/wwwroot/canvasgrid/

WORKDIR /inetpub/wwwroot/canvasgrid

EXPOSE 80
