# escape=` 

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base

LABEL maintainer='davidseandunn@gmail.com'

RUN apt-get update -yq \ `
    && apt-get install curl gnupg -yq \ `
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \ `
    && apt-get install nodejs -yq 

WORKDIR /source

COPY CanvasGridUI/package.json /source/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

COPY CanvasGridUI/* /source/
RUN npm run-script compile

# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /source

# Copy csproj and restore as distinct layers
COPY ./CanvasGridAPI/CanvasGridAPI/*.csproj ./
#COPY ["./CanvasGridAPI/CanvasGridAPI/*.csproj", "./"]
RUN dotnet restore

# Copy everything else and build
COPY ./CanvasGridAPI/CanvasGridAPI/* ./
RUN dotnet publish -c Release -o canvasgridapi

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /canvasgrid
COPY --from=build-env /source/canvasgrid .
RUN cp /source/dist/canvasgrid-ui/* /canvasgrid


EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "CanvasGridAPI.dll"]
