version: "3"

services:
    canvasgrid:
        build: ../../
        image: sdeeze/canvasgrid:${buildno-latest}
        container_name: canvasgrid
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment: 
            - ASPNETCORE_URLS=https://+;http://+;
        volumes:
            - /home/ubuntu/canvasgrid/Images:/canvasgrid/wwwroot/Images
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "QJyDHjjatZ6T3jwtP9Yr6SYj"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - mssql-server-linux-data:/mssql/data
