version: "3"

services:
    canvasgrid:
        build: ../../
        image: sdeeze/canvasgrid:${buildno-latest}
        container_name: canvasgrid
        restart: always
        ports:
            - "80:5000"
            - "443:5001"
        environment: 
            - ASPNETCORE_URLS=https://+;http://+;
