version: "3.7"

services:
    canvasgrid:
        build: ../../
        image: sdeeze/canvasgrid:${buildno-latest}
        container_name: canvasgrid
        restart: always
        ports:
            - "8001:80"
        environment: 
            - ASPNETCORE_URLS=https://+;http://+;
        volumes:
            - /home/ubuntu/canvasgrid/Images:/canvasgrid/wwwroot/Images
