version: "3"

services:
    canvasgrid:
        build: ../../
        image: sdeeze/canvasgrid:${buildno-latest}
        container_name: canvasgrid
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment: 
            - ASPNETCORE_URLS=https://+;http://+;
        volumes:
            - /home/ubuntu/canvasgrid/Images:./Images
