version: "3.7"

services:
    canvasgrid:
        build: ../../
        image: sdeeze/canvasgrid:${buildno-latest}
        container_name: canvasgrid
        restart: always
        ports:
            - "8001:80"
        environment: 
            - ASPNETCORE_URLS=https://+;http://+;
        volumes:
            - /home/ubuntu/canvasgrid/Images:/canvasgrid/wwwroot/Images
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        user: root
        restart: always
        environment:
            SA_PASSWORD: "PASSWORD_REPLACE"
            ACCEPT_EULA: Y
        ports:
            - "1433:1433"
        volumes:
            - mssql-server-linux-data:/var/opt/mssql/data

volumes:
  mssql-server-linux-data:
