# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

MAINTAINER Sean Dunn <davidseandunn@gmail.com>

WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
RUN dotnet publish -c release -o /canvasgridapi --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /canvasgridapi .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "canvasgridapi.dll"]
